//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multigyms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MG_Persona()
        {
            this.MG_Pagos = new HashSet<MG_Pagos>();
            this.mg_reviews = new HashSet<mg_reviews>();
            this.MG_Visitas = new HashSet<MG_Visitas>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Passw { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public System.DateTime FecNacimiento { get; set; }
        public string Celular { get; set; }
        public System.DateTime FecIngreso { get; set; }
        public int Id_Plan { get; set; }
        public short CredDisponible { get; set; }
        public Nullable<int> Id_empresa { get; set; }
        public bool Activo { get; set; }
        public string Token { get; set; }
        public Nullable<int> Id_Ciudad { get; set; }
        public string Sexo { get; set; }
        public string LastPushId { get; set; }
        public string LastImei { get; set; }
        public Nullable<int> LastTipoApp { get; set; }
    
        public virtual MG_Ciudades MG_Ciudades { get; set; }
        public virtual MG_Empresa MG_Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_Pagos> MG_Pagos { get; set; }
        public virtual MG_Planes MG_Planes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mg_reviews> mg_reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MG_Visitas> MG_Visitas { get; set; }
    }
}
