//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multigyms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_Pagos
    {
        public int Id { get; set; }
        public int Id_persona { get; set; }
        public System.DateTime FecPago { get; set; }
        public short Monto { get; set; }
        public Nullable<int> Id_FormaPago { get; set; }
    
        public virtual MG_FormaPago MG_FormaPago { get; set; }
        public virtual MG_Persona MG_Persona { get; set; }
    }
}
