//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multigyms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MG_Visitas
    {
        public int Id { get; set; }
        public int Id_Persona { get; set; }
        public int Id_Gym { get; set; }
        public Nullable<System.DateTime> FecVisita { get; set; }
        public short CredUsado { get; set; }
    
        public virtual MG_Gym MG_Gym { get; set; }
        public virtual MG_Persona MG_Persona { get; set; }
    }
}
